services:
  # 1. DATABASE SERVICES
  db:
    image: postgres:15-alpine
    container_name: mars_db_local
    restart: always
    environment:
      - POSTGRES_USER=commander
      - POSTGRES_PASSWORD=ares_pass
      - POSTGRES_DB=mars_database
    ports:
      - "5432:5432"
    volumes:
      #  We run the initialization script so that the tables are created automatically
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mars_data:/var/lib/postgresql/data

  # 2. APP SERVICE
  app:
    build: .
    container_name: mars_app_local
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Specify the address of the INTERNAL database (db is the name of the service mentioned above)
      - POSTGRES_URL=postgresql://commander:ares_pass@db:5432/mars_database
      - ADMIN_PASSWORD=adm
    depends_on:
      - db

volumes:
  mars_data: