/**
 * SPACE SURVIVAL DATABASE INITIALIZATION
 * Run this script in your Vercel Storage Query or local Postgres tool.
 */

-- 1. Create a separate SCHEMA for the project
CREATE SCHEMA IF NOT EXISTS mars_mission;

-- 1. Drop tables if they exist (to start fresh if needed)
-- Note: Drop results first because it depends on teams (Foreign Key)
DROP TABLE IF EXISTS mars_mission.results;
DROP TABLE IF EXISTS mars_mission.teams;

-- 2. Create Teams Table
-- This stores the list of available teams
CREATE TABLE mars_mission.teams (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  current_scenario VARCHAR(255) DEFAULT 'mars_01',
  -- Logic Flags
  is_unlocked BOOLEAN DEFAULT false,    -- Results visible for players
  has_commander BOOLEAN DEFAULT false,  -- Team already has a leader
  is_archived BOOLEAN DEFAULT false,    -- Hidden from active mission list
  -- Security: Unique token for team-based links
  access_token TEXT UNIQUE DEFAULT md5(random()::text),
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create Results Table
-- Stores player scores and links them to teams via ID
CREATE TABLE mars_mission.results (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  -- Link to team (CASCADE ensures player records are deleted if team is removed)
  team_id INT REFERENCES teams(id) ON DELETE CASCADE,
  -- Score logic: -1 means mission is "Pending" (not started/finished)
  score INT DEFAULT -1, 
  -- Selections: Stored as JSON array. NULL until mission is finished.
  selections JSONB DEFAULT NULL,
  -- Security: Unique token for personal links
  access_token TEXT UNIQUE DEFAULT md5(random()::text),
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Creating a settings table
CREATE TABLE mars_mission.settings (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

-- Add the initial language setting (optional)
INSERT INTO mars_mission.settings (key, value) VALUES ('system_language', 'it');